### ISSUE TITLE
Question: how could we make it simple for anyone to test a specific PR from Docker?

### ISSUE THREAD

**Issue by terrywbrady** [DSpace-Labs/DSpace-Docker-Images#10]
Would it be possible to make the instructions so simple that any repository manager with a local Docker instance could test a specific version of the code?

When travis performs the automated build of code for a specific PR, could the built assets be retrievable for quick testing?  Or, would the download of built assets be so slow that it would be advisable just to build locally?

If a user must build locally, what can we do to make it as easy as possible?

**Comment by pnbecker** [comment]
I always imagined a Webservice, where I would see a list of Pull-Requests, could add a local.cfg, and would get an URL where an instance of DSpace would be running the Pull-Request I decided to test, for the next 30 minutes or so.

**Comment by terrywbrady** [comment]
Options

1. If the contributor configures automated Docker builds from their repo, then images would be available for automated build.
2. PR builds could be performed and pushed during travis build
3. We could automatically clone PR's to DSpace-Labs/DSpace and then build from there.
4. We could manually build PR images when we determine that this will be useful for testing.

**Comment by terrywbrady** [comment]
- Option 1: Add Docker Build to travis: https://github.com/DSpace/DSpace/pull/2308
- Option 2: Explore options in new Docker Build system: https://stackoverflow.com/questions/54203689/docker-cloud-automated-build-automatically-publish-an-image-for-a-pull-request

**Comment by terrywbrady** [comment]
See https://github.com/DSpace-Labs/DSpace-Docker-Images/issues/103

If we decide to explore option 3, we should create a new issue
