### ISSUE TITLE
Create DSpace 7 Entities instruction page

### ISSUE THREAD

**Issue by terrywbrady** [DSpace-Labs/DSpace-Docker-Images#120]
@benbosman recommended modeling this new page on the Running DSpace 7 page

**Comment by benbosman** [comment]
https://dspace-labs.github.io/DSpace-Docker-Images/documentation/run.DSpace7Entities.html is already looking good.
Some useful things to add are:
* After the applications have started, discovery reindexing will start. This will require approximately 5 minutes as well. You can view the status at http://localhost:8080/spring-rest/#http://localhost:8080/spring-rest/api/discover/search/objects. It is expected to contain 462 totalElements.
* Collections and items of interest
  * http://localhost:3000/items/a23eae5a-7857-4ef9-8e52-989436ad2955 represents a journal with journal volumes, issues and articles, as detailed in https://docs.google.com/document/d/1X0XsppZYOtPtbmq7yXwmu7FbMAfLxxOCONbw0_rl7jY/edit#heading=h.p5ja9m7zrpks
  * http://localhost:3000/collections/dd1240ae-d7dd-405c-bdc3-d6c960609433 contains publications which contain a combination of plain-text authors and related author entities. It also contains relations to Research Projects and Organizational Units, as detailed in https://docs.google.com/document/d/1X0XsppZYOtPtbmq7yXwmu7FbMAfLxxOCONbw0_rl7jY/edit#heading=h.x0m096abh8pu. Navigating to e.g. a Person will reveal their relations to Publications, Research Projects and Organizational Units.
  * The submission can be verified in one of the collections in http://localhost:3000/communities/c0e4de93-f506-4990-a840-d406f6f2ada7 where the workflow is enabled. You can use the accounts mentioned above to perform the submission and workflow steps. The admin account can perform the submission and all workflow steps as well

**Comment by terrywbrady** [comment]
@benbosman , thanks for these notes.  I have added them to the documentation: https://dspace-labs.github.io/DSpace-Docker-Images/documentation/run.DSpace7Entities.html
