### ISSUE TITLE
CORS header missing

### ISSUE THREAD

**Issue by TcaManager** [DSpace-Labs/DSpace-Docker-Images#145]
Hi,
Launching D7 job, DSpace from docker-compose.
All containers started, after I filled the override file.
I get errors when trying to connect to API on port 8080 from port 3000 (angular client). Is there anything I forgot in the configuration? Thanks.

**Comment by TcaManager** [comment]
What I don't get is why this line
rest.cors.allowed-origins = *
In /dspace/config/modules/rest.cfg doesn't solve the problem.

**Comment by tdonohue** [comment]
@TcaManager : I'd recommend *not* using this old `DSpace-Labs` project for DSpace 7 in Docker. It's no longer being maintained, as the DSpace 7 Docker stuff has move into the official DSpace codebase.  See the README here on how to run DSpace 7 using Docker Compose: https://github.com/DSpace/DSpace/blob/master/dspace/src/main/docker-compose/README.md
