### ISSUE TITLE
Explore DockerHub automated builds for DSpace branches

### ISSUE THREAD

**Issue by terrywbrady** [DSpace-Labs/DSpace-Docker-Images#36]
This is a paid feature, we would need to present a case to the steering group for approval.

The cost should be modest.

https://docs.docker.com/docker-hub/builds/

**Comment by hardyoyo** [comment]
+1

**Comment by terrywbrady** [comment]
I have successfully set up automated builds from the terrywbradyC9/dspace repo.  

Once the dockerfiles have been merged into DSpace/DSpace, this will be possible.
