### ISSUE TITLE
Update `ingestAIP.sh` to do a SITE AIP import?

### ISSUE THREAD

**Issue by tdonohue** [DSpace-Labs/DSpace-Docker-Images#52]
Just noting that the `ingetAIP.sh` script currently does its own parsing/looping over Community/Collection/Item AIPs (instead of restoring from a Site-level AIP), e.g.
https://github.com/DSpace-Labs/DSpace-Docker-Images/blob/master/add-ons/mount_ingest_tools/ingestAIP.sh

We may want to consider updating to do an import starting at the SITE level AIP (this is the same command we use on demo.dspace.org to do a full site "reset"):

`/dspace/bin/dspace packager -u -r -a -f -t AIP -e test@test.edu -o skipIfParentMissing=true -o createMetadataFields=true SITE@[handle].zip`

The extra benefit here is that this will also create any permissions/users/groups that are stored in the SITE AIP.  It also includes flags to auto-create any missing/custom metadata fields, and to skip any "parent not found errors".

The full reset script for demo.dspace.org site is in GitHub here (in case it's useful to see the entire restore process run on demo): https://github.com/DSpace-Labs/demo.dspace.org-site/blob/master/scripts/linux/reset-dspace-content#L234

**Comment by terrywbrady** [comment]
@tdonohue , thanks for this.  

Are you aware of any useful collections of AIP's to consider documenting for use?

In this example, it appears that you ingest everything from a single AIP zip file.  I wonder if that would perform faster than the approach that I have in place.

**Comment by tdonohue** [comment]
@terrywbrady : Just to clarify, I'm not ingesting from a single AIP...The DSpace AIP packager is "smart" enough to locate other AIPs in the same directory. If you pass it the SITE AIP, that AIP knows the filename of all COMMUNITY AIPs.  Each COMMUNITY AIP knows the name of associated COLLECTION AIPs, and each COLLECTION AIP knows the name of associated ITEM AIPs.  So, the DSpace AIP packager can "crawl" the directory of AIPs from any specific starting AIP file. 

Just passing the SITE AIP is the recommended route if you want to restore an entire "Site". More on restoring a full site at: https://wiki.duraspace.org/display/DSDOC6x/AIP+Backup+and+Restore#AIPBackupandRestore-RestoringEntireSite

While this isn't of much use for this use case, you also can start from individual Community or Collection AIPs. So, if you want to only restore a specific Community or Collection, then you'd pass the packager the single Community or Collection AIP, and it would "crawl" the directory of AIPs starting from that specific Community or Collection.  

The demo.dspace.org content is the only AIP content I have at this time. It's not very realistic data, but it could be reused.  You can find these AIPs on the demo.dspace.org server in the `~/AIP-restore` folder..it's roughly 2 Communities, 4 Collections, and around 40 Items.  If you need SSH access to that shared server, ping me on Slack.

**Comment by terrywbrady** [comment]
@tdonohue and I discussed making the demo.dspace.org AIP files available in a GitHub repo.

I will create a new DSpace-Labs repo for this purpose.

**Comment by terrywbrady** [comment]
Sample AIP files now contain SITE.zip files.

[The Library Code](https://www.the-library-code.de/) has offered to host larger AIP assets for the project.

There was a request at the Jan 2019 DCAT meeting to find volunteers to help curate these assets.  I think additional work will be needed to recruit volunteers for this task.

@pnbecker , fyi
