### ISSUE TITLE
Question: should we provide a set of scripts to make it easier to build/deploy to Docker?

### ISSUE THREAD

**Issue by terrywbrady** [DSpace-Labs/DSpace-Docker-Images#7]
If so, where should the source for these scripts reside?

How should these scripts be invoked?  (From the host computer, or within a bash window in Docker)?

**Comment by pnbecker** [comment]
I started to add config files to my developer images. Thinks like bash_history, which contains sophisticated maven commands, bashrc with aliases and vimrc to configure the editor of my choice. If these are part of the image, every other helper script should be too.

**Comment by terrywbrady** [comment]
@pnbecker Take a look at the existing images and tutorial.  As I have enhanced these images, I have moved most of the build/deploy steps outside of the docker image.  I would like to determine if we also need images from which the build will be invoked.
