### ISSUE TITLE
Question: if we are creating a volume to persist the assetstore, solr, etc, should we also place the pgdata volume within that larger volume?

### ISSUE THREAD

**Issue by terrywbrady** [DSpace-Labs/DSpace-Docker-Images#8]
The primary advantage of this approach is that it would require one fewer volume file to test.

On the other hand. it would make it more complicated to load up a large scale database volume.

**Comment by pnbecker** [comment]
I think multiple volumes are fine. We are also running multiple containers (one for the database and one for the servlet container, which is how containers should be used). The downside to use one volume, would be that Docker would have to synchronize the use of the volume between all containers that accesses the same volume. I don't see much benefit in that.
