### ISSUE TITLE
Question: is it possible to share pre-built volumes to facilitate quick testing?

### ISSUE THREAD

**Issue by terrywbrady** [DSpace-Labs/DSpace-Docker-Images#9]
If so, there volumes would already contain sample users, communities, collections, items, and bitstreams.

These files would provide a quick restart point for someone deploying a new container. 

These volumes would need to be tagged to specific DSpace releases.

**Comment by pnbecker** [comment]
I don't think it is. The idea of containers is to be build easily and destroyed afterwards. Volumes are used to persist some data, but not to provide data for new containers. I might be wrong, but that is my understanding so far.
